language: node_js
node_js:
  - '14.0'
cache: npm
install:
  - npm install -g firebase-tools
  - npm install -g gatsby
  - npm ci
script:
  - npm run build
after_success:
  - firebase deploy --except functions --token $FIREBASE_TOKEN
branches:
  only:
    - main