language: node_js
node_js:
  - '14.0'
cache: npm
env:
  - COCKPIT_TOKEN=$COCKPIT_TOKEN COCKPIT_URL=$COCKPIT_URL
install:
  - npm install -g gatsby
  - npm ci
script:
  - npm run build
after_success:
  - npx firebase deploy --except functions --token $FIREBASE_TOKEN
branches:
  only:
    - main
